{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9336dd56-4728-4348-bce3-c81e9eba2708",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C:\\Users\\thais\\Documents\\00_MACHINE_LEARNING\n"
     ]
    }
   ],
   "source": [
    "cd C:/Users/thais/Documents/00_MACHINE_LEARNING/\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0c7d9626-e372-4e19-9f8c-ed478131e4c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "from sklearn.preprocessing import RobustScaler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "26a6b616-3ec8-4fab-888e-79834f55de4f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-12 17:25:14.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.072 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.143 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-11-12 17:25:14.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# Cargar el modelo y el escalador guardados\n",
    "with open('random_forest_model.pkl', 'rb') as model_file:\n",
    "    rf_model = pickle.load(model_file)\n",
    "\n",
    "with open('robust_scaler.pkl', 'rb') as scaler_file:\n",
    "    scaler = pickle.load(scaler_file)\n",
    "\n",
    "# Función para predecir y mostrar resultados\n",
    "def predict_and_display(input_data):\n",
    "    # Escalar las características de entrada usando el escalador cargado\n",
    "    input_scaled = scaler.transform(input_data)\n",
    "\n",
    "    # Realizar predicción\n",
    "    y_pred = rf_model.predict(input_scaled)\n",
    "    y_prob = rf_model.predict_proba(input_scaled)[:, 1]  # Probabilidad de la clase positiva\n",
    "\n",
    "    # Mostrar resultados\n",
    "    st.write(f\"Predicción: {'Sí' if y_pred[0] == 1 else 'No'}\")\n",
    "    st.write(f\"Probabilidad de 'Sí': {y_prob[0]:.2f}\")\n",
    "\n",
    "# Interfaz de usuario de Streamlit\n",
    "st.title(\"Predicción de Depósito Bancario\")\n",
    "\n",
    "st.sidebar.header(\"Configuración de Entrada\")\n",
    "\n",
    "# Cargar datos procesados (puedes cambiar esta ruta si lo deseas)\n",
    "banc_transformed = pd.read_csv('banc_transformed.csv')\n",
    "\n",
    "# Mostrar las primeras filas del DataFrame para entender las variables\n",
    "st.write(\"Primeras filas del dataset:\")\n",
    "st.write(banc_transformed.head())\n",
    "\n",
    "# Ingresar los datos de todas las columnas\n",
    "st.sidebar.header(\"Ingrese los datos del cliente\")\n",
    "\n",
    "# Variables numéricas\n",
    "edad = st.sidebar.slider('Edad', min_value=18, max_value=100, value=18)\n",
    "saldo = st.sidebar.slider('Saldo en cuenta', min_value=0, max_value=100000, value=0)\n",
    "duracion = st.sidebar.slider('Duración de la llamada (minutos)', min_value=0, max_value=1000, value=0)\n",
    "pdays = st.sidebar.slider('Días desde el último contacto', min_value=-1, max_value=1000, value=30)\n",
    "\n",
    "# Variables categóricas (usar selectbox para las variables categóricas)\n",
    "default = st.sidebar.selectbox('¿Tiene morosidad?', ['No', 'Sí'])\n",
    "housing = st.sidebar.selectbox('¿Tiene hipoteca?', ['No', 'Sí'])\n",
    "loan = st.sidebar.selectbox('¿Tiene crédito personal?', ['No', 'Sí'])\n",
    "contact_prev = st.sidebar.selectbox('¿Fue contactado anteriormente?', ['No', 'Sí'])\n",
    "\n",
    "# Estado civil (se puede usar multiple selectbox para las tres opciones)\n",
    "marital = st.sidebar.selectbox('Estado Civil', ['Divorciado', 'Casado', 'Soltero'])\n",
    "\n",
    "# Nivel educativo (también con selectbox para las tres opciones)\n",
    "education = st.sidebar.selectbox('Nivel Educativo', ['Primario', 'Secundario', 'Terciario'])\n",
    "\n",
    "# Convertir las respuestas categóricas a formato numérico\n",
    "default_numeric = 1 if default == 'Sí' else 0\n",
    "housing_numeric = 1 if housing == 'Sí' else 0\n",
    "loan_numeric = 1 if loan == 'Sí' else 0\n",
    "contact_prev_numeric = 1 if contact_prev == 'Sí' else 0\n",
    "\n",
    "# Convertir las categorías de estado civil y nivel educativo en variables binarias\n",
    "marital_divorced = 1 if marital == 'Divorciado' else 0\n",
    "marital_married = 1 if marital == 'Casado' else 0\n",
    "marital_single = 1 if marital == 'Soltero' else 0\n",
    "\n",
    "education_primary = 1 if education == 'Primario' else 0\n",
    "education_secondary = 1 if education == 'Secundario' else 0\n",
    "education_tertiary = 1 if education == 'Terciario' else 0 \n",
    "education_unknown = 1 if education == 'Desconocido' else 0 \n",
    "\n",
    "# Crear el DataFrame de entrada per a la predicció\n",
    "input_data = pd.DataFrame({\n",
    "    'age': [edad],\n",
    "    'balance': [saldo],\n",
    "    'duration': [duracion],\n",
    "    'pdays': [pdays],\n",
    "    'default_numeric': [default_numeric],\n",
    "    'housing_numeric': [housing_numeric],\n",
    "    'loan_numeric': [loan_numeric],\n",
    "    'contact_previ_numeric': [contact_prev_numeric],\n",
    "    'marital_divorced': [marital_divorced],\n",
    "    'marital_married': [marital_married],\n",
    "    'marital_single': [marital_single],\n",
    "    'education_primary': [education_primary],\n",
    "    'education_secondary': [education_secondary],\n",
    "    'education_tertiary': [education_tertiary],\n",
    "    'education_unknown': [education_unknown]\n",
    "})\n",
    "\n",
    "input_data = input_data[scaler.feature_names_in_]\n",
    "\n",
    "input_scaled = scaler.transform(input_data)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67cd89df-8a76-4fcd-8555-573203130adc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
